config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/home'
  get 'static_pages/about_me'
  get 'static_pages/services'
  get 'static_pages/forms'
  get 'static_pages/patient_info'
  get 'static_pages/contact'
  root 'static_pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about_me
  end

  def services
  end

  def forms
  end

  def patient_info
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HigherPeaks</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body> 
    <!-- navbar-expand-lg -->

    <nav class="navbar navbar-expand-lg fixed-top navbar-dark bg-dark">
      <!-- <a class="navbar-brand" href="#">Higher Peaks Counseling</a> -->
      <a class="navbar-brand">
        <%= link_to 'Higher Peaks Counseling', static_pages_home_path, class: 'navbar-brand' %>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <%= link_to 'Home', static_pages_home_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'About Me', static_pages_about_me_path, class: 'nav-link' %>
          </li>
          <!-- <li class="nav-item">
            <%= link_to 'Services', static_pages_services_path, class: 'nav-link' %>
          </li> -->
          <!-- <li class="nav-item">
            <%= link_to 'Forms', static_pages_forms_path, class: 'nav-link' %>
          </li> -->
          <!-- <li class="nav-item"> -->
           <!--  <%= link_to 'Patient Info', static_pages_patient_info_path, class: 'nav-link' %>
          </li> -->
          <li class="nav-item">
            <%= link_to 'Contact', static_pages_contact_path, class: 'nav-link' %>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Forms
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="/Consent.pdf" type="application/pdf"   height="300px" width="100%" class="responsive" target="_blank">Consent for Release of Infomation</a>
              <!-- <a href="/Consent.pdf">download</a> -->
              <a class="dropdown-item" href="/Change of Information.pdf" type="application/pdf"   height="300px" width="100%" class="responsive" target="_blank">Patient Change of Information</a>
              <!-- <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="#">Something else here</a> -->
            </div>
          </li>
          <!-- <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Dropdown
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="#">Action</a>
              <a class="dropdown-item" href="#">Another action</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="#">Something else here</a>
            </div>
          </li> -->
          <!-- <li class="nav-item">
            <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
          </li> -->
        </ul>
        <!-- <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form> -->
      </div>
    </nav>

    <%= yield %>

  </body>
</html>

app/views/static_pages/about_me.html.erb
<div class="about_hero">
  <br /><br /><br /><br /><br /><br /><br />
 
  <br /><br />

  <div class="box row col-8 offset-2 text-center">
    <div class="col-sm-12">
      <div class="welcome">
        <br /><!-- <br /><br /> -->
        <div class="aboutMe">
          <img src="/me2.jpg">
        </div>
        <p>I am a Licensed Clinical Social Worker with over 20 years experience in the field of social services. My education consists of a Bachelors of Science in Secondary Education from Kutztown University and my Masters of Social Work from Colorado State University. I incorporate a variety of treatment modalities, to include Cognitive Behavior and Dialectical Behavior Therapy to address concerns related to:</p>

          <p>Anxiety Disorders &#9679 Behavioral and Discipline Challenges &#9679 Anger and Stress Management &#9679 Criminal Thinking and Behavior &#9679 Sexual Issues and Addiction &#9679 Sexual Victimization &#9679 Mood Disorders &#9679 Personality Disorders &#9679 Individuals with Different Abilities &#9679 Self-Image and Self Esteem Issues</p>

        <p>I have worked and will continue to work with teens, adults, individuals with different intellectual/developmental abilities, and the LGBTQ community. I am an approved SOMB provider and work closely with The Resource Exchange. </p>
        <br /><!-- <br /><br /> -->
        <h4>Please contact me to schedule a free initial consultation</h4>
        <br />
        <span class="fa fa-phone fa-2x phone-button">                       719-287-1461</span>
        <br />
        <br />
        <span class="fa fa-envelope fa-2x envelope-button"><a href="mailto:laureenq10.gmail.com? ">                       laureenq10@gmail.com</a></span>
        <br />
        <!-- <h6>Click below to schedule an appointment</h6>
        <br />
        <%= link_to 'Schedule An Appointment', '#', class: 'btn btn-success' %> -->
        <br /><!-- <br /><br /> -->
      </div>
    </div>
    <!-- <div class="col-sm-4">
      <div class="aboutMe">
        <br />
        <h6>About Me</h6>
        <img src="/me.jpg">
        <p>As an experienced _______________ therapist, it is my honor to assist you in exploring your core issues and move toward a healthy, fulfilling life.</p>

        <p>I offer ________________ therapy sessions in and around Colorado Springs, Colorado.</p>
        <br />
      </div>
    </div> -->
  </div>
</div>

app/views/static_pages/contact.html.erb
<div class="contact_hero">
  <br /><br /><br /><br /><br /><br /><br />
 
  <br /><br />

  <div class="box row col-8 offset-2 text-left">
    <div class="col-sm-12 text-center">
      <br /><br />
      <div class="welcome">
        <h6>I am conveniently located in downtown Colorado Springs</h6>
        <br />
        <a href="https://www.google.com/maps/place/703+N+Tejon+St,+Colorado+Springs,+CO+80903/data=!4m2!3m1!1s0x8713453fdb86eceb:0x8abb63498ea059d1?sa=X&ved=2ahUKEwiWxYqEv_jnAhUMd6wKHQYlAPsQ8gEwAHoECAsQAQ" target="_blank">
          <img border="0" alt="703 N. Tejon St. Suite B" src="/map.png" width="700" height="350"></a>
        <br /><br />
        <a href="https://www.google.com/maps/place/703+N+Tejon+St,+Colorado+Springs,+CO+80903/data=!4m2!3m1!1s0x8713453fdb86eceb:0x8abb63498ea059d1?sa=X&ved=2ahUKEwiWxYqEv_jnAhUMd6wKHQYlAPsQ8gEwAHoECAsQAQ" target="_blank">703 N. Tejon St. Suite B</a>

        <br /><br /><br />
        <h4>Please contact me to schedule a free initial consultation</h4>
        <br />
        <span class="fa fa-phone fa-2x phone-button">                       719-287-1461</span>
        <br />
        <br />
        <span class="fa fa-envelope fa-2x envelope-button"><a href="mailto:laureenq10.gmail.com? ">                       laureenq10@gmail.com</a></span>
        <br />
        <!-- <h6>Click below to schedule an appointment</h6>
        <br />
        <%= link_to 'Schedule An Appointment', '#', class: 'btn btn-success' %> -->
        <br /><!-- <br /><br /> -->
      </div>
    </div>
  </div>
</div>

<!-- <br />

<%= image_tag 'map.png' %>

<div class="row feature text-center">
<div class="box col-10 offset-1 text-center">
  <div class="col-12 col-sm">
    <h3>Welcome</h3>
    <h4>Asking for help is a sign of strength</h4>
    <p>Whether you’re experiencing depression or anxiety, or you need help with managing stress, it takes courage to ask for help. Admitting you can’t do everything on your own, is the first step toward achieving wellness in a fast paced, demanding world.</p>

    <p>The good news is, asking for help gets easier with a little practice. The way in which we cope in the world is greatly influenced by how we see the world. Asking for help, and obtaining a fresh perspective is often the first and most profound step toward developing the mental muscle needed to become stronger. The more support you gain, the better equipped you will be to take on bigger challenges and achieve more successes.</p>
  </div>
  <div class="col-12 col-sm">
    <h3>Feature 2</h3>
  </div>
  <div class="col-12 col-sm">
    <h3>Feature 3</h3>
  </div>
</div> -->

app/views/static_pages/forms.html.erb
<div class="forms_hero">
  <br /><br /><br /><br /><br /><br /><br />
  

  <br /><br />

  <div class="box row col-8 offset-2 text-left">
    <div class="col-sm-12 text-center">
      <div class="welcome">
        <br />
        <h4>Please fill out the following forms</h4>
        <br />
      </div>
    </div>
  </div>
</div>

<!-- <br />
<div class="row feature text-center">
<div class="box col-10 offset-1 text-center">
  <div class="col-12 col-sm">
    <h3>Welcome</h3>
    <h4>Asking for help is a sign of strength</h4>
    <p>Whether you’re experiencing depression or anxiety, or you need help with managing stress, it takes courage to ask for help. Admitting you can’t do everything on your own, is the first step toward achieving wellness in a fast paced, demanding world.</p>

    <p>The good news is, asking for help gets easier with a little practice. The way in which we cope in the world is greatly influenced by how we see the world. Asking for help, and obtaining a fresh perspective is often the first and most profound step toward developing the mental muscle needed to become stronger. The more support you gain, the better equipped you will be to take on bigger challenges and achieve more successes.</p>
  </div>
  <div class="col-12 col-sm">
    <h3>Feature 2</h3>
  </div>
  <div class="col-12 col-sm">
    <h3>Feature 3</h3>
  </div>
</div> -->

app/views/static_pages/home.html.erb
<div class="hero">
  <br /><br /><br /><br /><br /><br /><br />
  <div class="frosty col-10 offset-1 text-center">
    <br />
    <h1>Higher Peaks Counseling</h1>
    <!-- <br /> -->
    <h2>Private Therapy by Laureen Quinn, LCSW</h2>
    <br />
  </div>

  <br /><br />

  <div class="box row col-8 offset-2 text-left">
    <div class="col-sm-8">
      <div class="welcome">
        <br />
        <h3>Welcome!</h3>
        <br />
        <h4>Asking for help is a sign of strength</h4>
        <br />
        <p>Let’s be real with each other. Life can sometimes feel dark. I want to help you navigate the muddy waters so you may find your way to clarity. I want to help you see the happiness you deserve. Together we can discover the path to get you there.</p>
        <!-- <p>Let’s be real with each other. Life can be hard. I want to be your ally. To sit WITH you during trying times.  To help you navigate the muddy waters so you may find your way to clarity. To help you see the happiness you deserve, and the different paths to help get you there. </p> -->

        <p>Since age 19, I’ve worked in a variety of jobs in the social services field. Throughout my career many people from all walks of life have helped me become the therapist I am today. The teens I worked with in the juvenile treatment facilities and in the community taught me that compassion and patience can create a brighter future for the next generation. While assisting individuals with different abilities I learned that we are all capable of reaching our truest potential if we have someone believe in us.  I have also learned that empathy can help individuals who engage in unhealthy behaviors. I now know and believe that with compassion, patience, belief, and empathy comes healing.</p>
        <!-- <p>Since age 19, I’ve worked in a wide variety of jobs in the social services field. My entire career, people from all walks of life have helped me become the therapist I am today. The teens I worked with in juvenile treatment facilities and in the community taught me that compassion and patience can create a brighter future for the next generations. Assisting individuals with different abilities showed me that we are all capable of reaching our truest potential if we have someone believe in us. And I have learned that by understanding why individuals engage in unhealthy behaviors, often landing them in the criminal system, empathy can help those individuals heal and create a safer place for our community.</p> -->


        <!-- <p>Whether you’re experiencing depression or anxiety, or you need help with managing stress, it takes courage to ask for help. Admitting you can’t do everything on your own, is the first step toward achieving wellness in a fast paced, demanding world.</p>

        <p>The good news is, asking for help gets easier with a little practice. The way in which we cope in the world is greatly influenced by how we see the world. Asking for help, and obtaining a fresh perspective is often the first and most profound step toward developing the mental muscle needed to become stronger. The more support you gain, the better equipped you will be to take on bigger challenges and achieve more successes.</p> -->
        <br />
      </div>
    </div>
    <div class="col-sm-4">
      <div class="aboutMe">
        <br /><!-- <br /><br /><br /> -->
        <!-- <h6>About Me</h6> -->
        <img src="/me1.jpg">
        <br /><!-- <br /><br /> -->
        <p>Please contact me to schedule a free initial consultation</p>
        <!-- <br /> -->
        <span class="fa fa-phone fa-1x phone-button">                       719-287-1461</span>
        <br />
        <br />
        <span class="fa fa-envelope fa-1x envelope-button"><a href="mailto:laureenq10.gmail.com? ">                       laureenq10@gmail.com</a></span>
        <br />
        <!-- <p>Click below to schedule an appointment</p>
        <br />
        <%= link_to 'Schedule An Appointment', '#', class: 'btn btn-success' %>
        <br /><br /><br /> -->
        <!-- <p>As an experienced _______________ therapist, it is my honor to assist you in exploring your core issues and move toward a healthy, fulfilling life.</p>

        <p>I offer ________________ therapy sessions in and around Colorado Springs, Colorado.</p> -->
        <br />
      </div>
    </div>
  </div>
</div>

<!-- <div class="col-sm-12 text-center">
  <div class="welcome">
    <br /><br /><br />
    <h4>Please contact me to schedule a free initial consultation</h4>
    <br />
    <span class="fa fa-phone fa-2x phone-button">                       719-287-1461</span>
    <br />
    <br />
    <h6>Click below to schedule an appointment</h6>
    <br />
    <%= link_to 'Schedule An Appointment', '#', class: 'btn btn-success' %>
    <br /><br /><br />
  </div>
</div> -->

<!-- <div class="sBox row col-10 offset-1 text-center">
  <h4>Please contact me to schedule a free initial consultation</h4>
  <h5>719-287-1461</h5>
  <i class="fas fa-phone-alt">123-456-7890</i>
  <br />
  <%= link_to 'Schedule An Appointment', '#', class: 'btn btn-success' %>
<br /><br />
</div> -->

<!-- <br />
<div class="row feature text-center">
<div class="box col-10 offset-1 text-center">
  <div class="col-12 col-sm">
    <h3>Welcome</h3>
    <h4>Asking for help is a sign of strength</h4>
    <p>Whether you’re experiencing depression or anxiety, or you need help with managing stress, it takes courage to ask for help. Admitting you can’t do everything on your own, is the first step toward achieving wellness in a fast paced, demanding world.</p>

    <p>The good news is, asking for help gets easier with a little practice. The way in which we cope in the world is greatly influenced by how we see the world. Asking for help, and obtaining a fresh perspective is often the first and most profound step toward developing the mental muscle needed to become stronger. The more support you gain, the better equipped you will be to take on bigger challenges and achieve more successes.</p>
  </div>
  <div class="col-12 col-sm">
    <h3>Feature 2</h3>
  </div>
  <div class="col-12 col-sm">
    <h3>Feature 3</h3>
  </div>
</div> -->

app/views/static_pages/patient_info.html.erb
<h1>StaticPages#patient_info</h1>
<p>Find me in app/views/static_pages/patient_info.html.erb</p>

app/views/static_pages/services.html.erb
<div class="services_hero">
  <br /><br /><br /><br /><br /><br /><br />
  

  <br /><br />

  <div class="box row col-8 offset-2 text-center">
    <div class="col-sm-12">
      <div class="welcome">
        <br /><br /><br />
        <h6>Write a paragraph about the services that you offer</h6>
        <br /><br /><br />
        <h4>Please contact me to schedule a free initial consultation</h4>
        <br />
        <span class="fa fa-phone fa-2x phone-button">                       719-287-1461</span>
        <br />
        <br />
        <h6>Click below to schedule an appointment</h6>
        <br />
        <%= link_to 'Schedule An Appointment', '#', class: 'btn btn-success' %>
        <br /><br /><br />
      </div>
    </div>
    <!-- <div class="col-sm-4">
      <div class="aboutMe">
        <br />
        <h6>About Me</h6>
        <img src="/me.jpg">
        <p>As an experienced _______________ therapist, it is my honor to assist you in exploring your core issues and move toward a healthy, fulfilling life.</p>

        <p>I offer ________________ therapy sessions in and around Colorado Springs, Colorado.</p>
        <br />
      </div>
    </div> -->
  </div>
</div>